[package]
org = "ballerina"
name = "random"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["pseudo-random"]
repository = "https://github.com/ballerina-platform/module-ballerina-random"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.7.0"

[platform.java17]
graalvmCompatible = true
